---
kind: pipeline
name: linux-pipeline-jdk11
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: mavenjdk11
    pull: always
    image: docker.io/maven:3.8.4-jdk-11-slim
    commands:
      - mvn -V clean verify --fail-at-end --batch-mode
